fs:
  default: local
  list:
    hdfs:
      type: hdfs
      url: hdfs://hdfs@nameservice1?cdh5-1.sm-soft.ru:8020,cdh5-4.sm-soft.ru:8020
      workDir: /tmp/gudata/source/ds/source/year=2021/month=03/day=03/hour=08
    local:
      type: local
      workDir: .
    kafka:
      type: kafka
      workDir: /
